#!/bin/sh
set -e

ADDON=ccu-modbus
BASE=/usr/local/addons/$ADDON
CONF=/usr/local/etc/config/addons/$ADDON
WEBLINK=/usr/local/etc/config/addons/www/$ADDON
RCD=/usr/local/etc/config/rc.d

mkdir -p "$BASE/bin" "$BASE/www" "$CONF" /usr/local/etc/config/addons/www "$RCD"

ARCH="$(uname -m)"
case "$ARCH" in
  x86_64|amd64) SRC=bin/linux-amd64/ccu-modbusd ;;
  aarch64|arm64) SRC=bin/linux-arm64/ccu-modbusd ;;
  armv7l|armv6l|arm) SRC=bin/linux-arm/ccu-modbusd ;;
  *) echo "Unsupported architecture: $ARCH"; exit 1 ;;
esac

cp -f "$SRC" "$BASE/bin/ccu-modbusd"
chmod 755 "$BASE/bin/ccu-modbusd"
cp -f bin/update_addon "$BASE/bin/update_addon"
chmod 755 "$BASE/bin/update_addon"
cp -f VERSION "$BASE/VERSION"

cp -f rc.d/ccu-modbus "$RCD/ccu-modbus"
chmod 755 "$RCD/ccu-modbus"

rm -rf "$BASE/www"/*
cp -af www/. "$BASE/www/"
rm -rf "$WEBLINK"
ln -s "$BASE/www" "$WEBLINK"

if [ ! -f "$CONF/config.json" ]; then
  cp -f examples/config.json "$CONF/config.json"
fi

touch /usr/local/etc/config/hm_addons.cfg
"$BASE/bin/update_addon" ccu-modbus /addons/ccu-modbus/index.cgi CCU-Modbus "Modbus TCP Interface" "Modbus TCP interface"

sync
exit 0
